---
image: quay.io/centos/centos:stream9-minimal

before_script:
  - microdnf install -y --nodocs --setopt=install_weak_deps=0 findutils git-core

default:
  tags:
    - itup-alm-x86

downstreamify:
  stage: test
  script:
    - bash downstreamify.sh
    - if [ -n "$(git diff)" ]; then echo "Looks like you need to run the downstreamify.sh script and commit the changes !"; git diff --color; exit 1; fi
no-log:
  stage: test
  script: |
    set +e
    no_log=$(grep -nr ' no_log:' roles | grep -v '"{{ no_log }}"')
    if [ -n "${no_log}" ]; then
      echo 'Please update the following no_log statement(s) with the "{{ no_log }}" value'
      echo "${no_log}"
      exit 1
    fi
