---
_redis_image: redis:7

redis_storage_size: 1Gi
# Here we use  _automationhub_ansible_com_automationhub to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_automationhub_ansible_com_automationhub']['spec'] }}"
redis_data_persistence: true
